# Generated by Django 4.2.17 on 2025-02-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='annee_candidature',
            new_name='annee_scolaire',
        ),
    ]
